[package]
name = "sorted"
version = "0.1.0"
edition = "2021"
autotest = false
publish = false

[lib]
proc_macro = true


[[test]]
name = "tests"
path = "tests/progress.rs"

[dev-dependencies]
trybuild = {version = '1.0.49', features = ['diff']}


[dependencies]
